### ISSUE TITLE
Pinterest button not working

### ISSUE THREAD

**Issue by AndB-GitHub** [jaredatch/EA-Share-Count#101]
Pinterest button not working. When I click on Pinterest button, a new window is opened but nothing appear, just a blank new window, no share or anything

**Comment by billerickson** [comment]
Can you provide a link to your site where this is happening?

**Comment by AndB-GitHub** [comment]
This is a screenshot after I pressed the Pinterest button
![pinterest not working](https://user-images.githubusercontent.com/38046064/45884827-2a3a6380-bdb5-11e8-9da1-563e1eac156b.jpg)

This is a link to one of my posts
https://www.natanstudio.com/foto-neonato-attesa-nascita-primi-giorni-di-vita/

**Comment by AndB-GitHub** [comment]
It works now, possibly it was my browser (?), anyway thank you!
