### ISSUE TITLE
FR: Update via CLI

### ISSUE THREAD

**Issue by JiveDig** [jaredatch/EA-Share-Count#102]
I've never done it, but seems like adding custom CLI commands is fairly straightforward. It would be cool to "prime the pump" and preload/update share counts without relying on admin page refresh via https://github.com/billerickson/Shared-Counts-Cache-Status.

I'm probably edge case of who would need this, but would be a nice addition :)

**Comment by billerickson** [comment]
I moved this issue over to the Shared Counts repo.

**Comment by JiveDig** [comment]
Doh! My instinct is still to search/type EA first. Sorry!
