### ISSUE TITLE
Add support for twitter share counts

### ISSUE THREAD

**Issue by billerickson** [jaredatch/EA-Share-Count#39]
Haven't tried it, but this might work: http://newsharecounts.com/

**Comment by billerickson** [comment]
Another option: http://opensharecount.com/

**Comment by billerickson** [comment]
I'm going to close this. All of these solutions are pretty hacky and I'm not comfortable supporting them in the core plugin. If necessary, this should be built as an add-on plugin.

**Comment by dreadedhamish** [comment]
I've emailed support@twitcount.com to ask if they can implement it from their end.  They already have implementations for Shareaholic, Sumome, AddThis and Jetpack.  If they won't then we should be able to pull it from there (in an add-on).

As I understand it opensharecount and newsharecount both access Twitters API for the last 7 days of data, and doesn't store it, whereas twitcount stores the accumulated shares.

**Comment by jaredatch** [comment]
If they would be open to work with us on this, I'd be open to getting a fix in core, assuming it was rather seamless for the user.

Please let us know what they say.

The biggest difference between what we do and what the other services you mentioned do, is that we fetch the counts and cache theme server-side. The other services load them dynamically on the front-end with javascript.

So TwitCount needs to have some sort of API we can call to get the count, but I don't see any mention of that on their site.

**Comment by dreadedhamish** [comment]
Yeah - I think their current integrations are running it frontend and then injecting that into the existing sharecount plugins mentioned above.  I'd settle for that but yeah - if we can get it cache that would be awesome.

**Comment by jaredatch** [comment]
Now on our radar for an future release!

**Comment by jaredatch** [comment]
In v1.8.1 branch (even though it will likely be released as 1.9).

https://github.com/jaredatch/EA-Share-Count/commit/b675e27e79a234b1f69fa765816545375501837f
