### ISSUE TITLE
Displaying after content issue

### ISSUE THREAD

**Issue by samikeijonen** [jaredatch/EA-Share-Count#43]
First, thank you for great plugin!

I have noticed one issue in several sites where I use the plugin. When I set Theme Location to **After content** or **Before and After Content**, social sharing buttons always remain before the content.

If I set Before and After Content, I get sharing button twice before the content.

![screenshot 2016-05-19 13 55 14](https://cloud.githubusercontent.com/assets/1820415/15391358/57f63a94-1dc9-11e6-9f6b-2e301c56875a.png)

I tried to check the code but didn't notice any problems and run out of time.

I'm using regular `_s` based theme, not Genesis or Theme Hook Alliance.

**Comment by samikeijonen** [comment]
Also got the same issue using Twenty 16.

**Comment by billerickson** [comment]
In the display functions we have can either echo the share buttons (if using a hook) or return the share buttons (if using a filter). The logic was messed up so it always echoed. This resulted in the share buttons appearing before the post content regardless of selected theme location if you were using the filter.

**Comment by samikeijonen** [comment]
Thanks!
