### ISSUE TITLE
Not showing up on Default Genesis Sample Theme

### ISSUE THREAD

**Issue by Jared-Williams** [jaredatch/EA-Share-Count#44]
I've been wanting to test this plugin out since I read Bill's post when you guys launched it. I setup a demo site with the new Genesis Sample Theme that was released a couple of days ago.

The site has no customization done to it, and I disable the few plugins I had active.

I uploaded the plugin and added the API Key, and selected "Before Content" on Posts. For some reason it is not displaying at all. I tried multiple settings to get it to display Before and/or After but I'm having no luck. 

I added the Genesis Simple Share plugin just to see if it would load Before Content and it does. You can see here - http://expressdemo.flywheelsites.com/sample-post/

I downloaded the plugin directly from this link - https://github.com/jaredatch/EA-Share-Count/archive/master.zip

An idea on what could be causing this issue?

Thanks in advance for any help!

**Comment by jaredatch** [comment]
Almost certain this is related to #43 but will wait for @billerickson to chime in :)

**Comment by Jared-Williams** [comment]
Thanks for the reply @jaredatch! Will wait for Bill 👍

**Comment by billerickson** [comment]
I believe @jaredatch  has fixed this in [issue/44](https://github.com/jaredatch/EA-Share-Count/tree/issue/44)

Can you download this version of the plugin and see if it works for you? https://github.com/jaredatch/EA-Share-Count/archive/issue/44.zip

**Comment by Jared-Williams** [comment]
@billerickson Yes, it works great! Thanks @jaredatch for the quick fix!

http://expressdemo.flywheelsites.com/sample-post/
