### ISSUE TITLE
Tumblr?

### ISSUE THREAD

**Issue by clarklab** [jaredatch/EA-Share-Count#47]
Is there a way to add a Tumblr share button? (or any custom service, really)

I know the SharedCount API won't return a count for it, but my build requirements include a 'share to tumblr' button.

**Comment by billerickson** [comment]
Yes, it's pretty simple. Here's sample code for adding a Reddit button: https://gist.github.com/billerickson/969f8ef0e980fe6e6345

**Comment by clarklab** [comment]
Perrrfect, thanks mang

**Comment by clarklab** [comment]
Doh! When I pasted in that snippet you shared, unedited, the share buttons disappear completely. It looks like some markup is still being inserted, it's just empty (loses all reference to each service), like so:

`<a href="" class="ea-share-count-button  " data-postid="1" "=""><span class="ea-share-count-icon-label"><i class="ea-share-count-icon "></i><span class="ea-share-count-label"></span></span><span class="ea-share-count"></span></a>`

**Comment by billerickson** [comment]
Oops, I forgot to `return $link` after modifying it. Updated the snippet.

**Comment by clarklab** [comment]
You da best

**Comment by billerickson** [comment]
👍

**Comment by clarklab** [comment]
ps: hopefully launching the new SXSW.com in late June, I'll send a note when it goes live
