### ISSUE TITLE
Template tags

### ISSUE THREAD

**Issue by clarklab** [jaredatch/EA-Share-Count#48]
This one is kinda dense, but I don't see it: is there a plain ol' template tag for inserting the share buttons? It works with the before/after theme location insertion, but I don't have a hook/filter in the ultra-specific place I need this to display.

**Comment by billerickson** [comment]
You can access the internal methods using the ea_share() function. So to output [the display() method](https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-front.php#L246), use `ea_share()->front->display( $location, $echo )`.

The location is simply added as a class to the wrapping div, the name isn't important.

If you need more control over the markup, you can use `ea_share()->front->link()`. [See code here](https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-front.php#L342) for more information on usage.

**Comment by billerickson** [comment]
I recommend you preface this with `if( function_exists( 'ea_share' ) )` . I've broken a client site or two by forgetting that and the client disabling the plugin :)
