### ISSUE TITLE
Labels and modal close not showing on email modal

### ISSUE THREAD

**Issue by AlphaBlossom** [jaredatch/EA-Share-Count#49]
I installed this using the new Genesis Sample theme and the email modal is not functioning correctly. The labels are not being output, as well as the modal close icon:

![screen shot 2016-06-01 at 10 19 36 pm](https://cloud.githubusercontent.com/assets/3486379/15734824/39499170-2848-11e6-8303-6ed71d75bf96.png)

```
<div id="easc-modal-wrap" style="display:none;">
	<div class="easc-modal">
		<span class="easc-modal-title"><!--? echo $labels['title']; ?--></span>
		<p>
			<label for="easc-modal-recipient"><!--? echo $labels['recipient']; ?--></label>
			<input type="text" id="easc-modal-recipient">
		</p>
		<p>
			<label for="easc-modal-name"><!--? echo $labels['name']; ?--></label>
			<input type="text" id="easc-modal-name">
		</p>
		<p>
			<label for="easc-modal-email"><!--? echo $labels['email']; ?--></label>
			<input type="text" id="easc-modal-email">
		</p>
		<p class="easc-modal-validation">
			<label for="easc-modal-validation"><!--? echo $labels['validation']; ?--></label>
			<input type="text" id="easc-modal-validation" autocomplete="off">
		</p>
		<p class="easc-modal-submit">
			<button id="easc-modal-submit"><!--? echo $labels['submit']; ?--></button>
		</p>
		<a href="#" id="easc-modal-close"><!--? echo $labels['close']; ?--></a>
		<div id="easc-modal-sent">Email sent!</div>
	</div>
</div>
```

I tested this locally so I don't have a link to share, but I tested it with no plugins, latest Genesis and WordPress and no theme modifications.

I also tested with Genesis directly with the same results. I haven't tried all options, but other buttons seem to be working properly.

I haven't entered an API key yet, but doesn't seem like that should be an issue for the labels not showing.

**Comment by billerickson** [comment]
Where did the code come from that you posted? All of the labels are commented out. If you [look here](https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-front.php#L208-L235) you'll see they aren't commented out in the actual plugin.

Your code has `<!--?` while ours has `<?`

I just spun up a clean WP install with genesis sample and the EASC plugin, no API key entered, and this is what the modal looks like:

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/453x450Y2g1a2t2W1Y3d/Screen%20Shot%202016-06-02%20at%208.00.16%20AM.png?v=cb901d0b)

**Comment by AlphaBlossom** [comment]
The code is the code that's being output, taken from Chrome inspector. It's a clean install as well, and this is the only plugin.

I recently used it on a non-Genesis site with no issues.

I'm using VVV with the standard configuration...maybe an issue there? I'm moving the site to staging today so I'll see if the issue goes away there.

Thanks for taking a look.

**Comment by jaredatch** [comment]
His server is not configured to accept PHP short tags `<?`. This is common among many hosts (Pagely for example).

We shouldn't be using short tags, using was simply an oversight (on my part IIRC).

**Comment by AlphaBlossom** [comment]
makes sense, thanks @jaredatch!
