### ISSUE TITLE
Links should have title attributes

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/EA-Share-Count#54]
`.ea-share-count-button` links should have title attribute.

Basically `title="Share on {$service}"` or similar.

**Comment by billerickson** [comment]
I started by doing `title="Share on ' . $link['label']` but we end up with "Share on Tweet" and "Share on Email". 

I think a better approach is to add another parameter to `$link` called `attr_title` or something similar. This way we can customize each link's title text, and it's filterable using the `ea_share_count_link` filter.

**Comment by billerickson** [comment]
See: https://github.com/jaredatch/EA-Share-Count/tree/issue/54

**Comment by jaredatch** [comment]
I think that's a good idea. Looks solid to me 👍
