### ISSUE TITLE
Use actual social service APIs rather than SharedCount

### ISSUE THREAD

**Issue by billerickson** [jaredatch/EA-Share-Count#57]
SharedCount.com is shutting down (see email below). 

It appears the issue is specific to SharedCount - they are using an old version of the Facebook API, and the newer ones no longer support bulk URL requests. Since we're only requesting single URLs, we can use the latest version of the Facebook API without any issues.

The downside is that instead of a single API call to SharedCount.com, we're not going to have an API call to [each service](http://stackoverflow.com/questions/5699270/how-to-get-share-counts-using-graph-api). 

I think we should update the backend UI so that for each service they can select whether or not to receive share counts. For many sites, the Facebook counts are all that matter - Google+ and Pinterest might always list 0 for their content. 

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/3W2M2I1w1l1v0o0Q0i0x/Screen%20Shot%202016-08-09%20at%2010.13.13%20AM.png?v=21ae81ad)

**Comment by joshuadavidnelson** [comment]
Well, that's a big thorn in the side of the plugin. I was really happy with their service and love this plugin - let me know if I can help the transition in any way.

**Comment by jaredatch** [comment]
Looks like we need to use FQL query to get all the various metrics for Facebook.

**Comment by billerickson** [comment]
Officially FQL is no longer available as of August 8, 2016: https://developers.facebook.com/docs/reference/fql/

[I got it working with FQL](https://gist.github.com/billerickson/80952dcf6dc85b0c05da320718565672), but I don't think we should release an update that uses this deprecated method that could stop working any day now.

It appears the only way to do it moving forward it with the Graph API, which only returns a single count for "engagement"

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/0d3K3r0f1P33051d2c1P/Screen%20Shot%202016-08-12%20at%2010.34.42%20AM.png?v=e7a89426)

Even when I drop that in the [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fconservativetribune.com%2Fus-divers-make-true-identity) I get "140160 likes, shares and comments (More Info)". 

The More Info link says likes and shares both show the same number - the combination of likes, shares and comments: 

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/3X1N2p310m3P1I0v2r2U/Screen%20Shot%202016-08-12%20at%2010.44.11%20AM.png?v=5e3f4480)

So should we only include a single facebook option and a single facebook number?

**Comment by billerickson** [comment]
See the [issue/57](https://github.com/jaredatch/EA-Share-Count/tree/issue/57) branch for a working version. Key points:

1. Facebook requires an Access Token for the counts to work. We should consider putting some sort of notice on update for users, since they'll get 0 counts until they update it.
2. I've set up the API queries for all our supported services, but only Facebook is selected by default. Again, a notice would be useful for users depending on other services.
3. Since Facebook only provides share_count and comment_count, I'm duplicating share_count for the like_count field, and total_count = share_count + comment count. [See here](https://github.com/jaredatch/EA-Share-Count/blob/issue/57/includes/class-core.php#L368-L371).

**Comment by billerickson** [comment]
Big problem. Facebook Access Tokens only last for one hour. You can go to the [Access Token Debugger](https://developers.facebook.com/tools/debug/accesstoken) to see how long your token lasts.

It looks [really complicated](http://stackoverflow.com/questions/12168452/long-lasting-fb-access-token-for-server-to-pull-fb-page-info) to make a permanent token, complicated enough that it's unrealistic for this plugin to expect it of users.

It appears [there's a process](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension) for converting this to a long-lived access token, which lasts for 60 days. The user provides us with their user token (lasts an hour), and we make a request to Facebook using that, our App ID, and our App Secret. Facebook returns the "long lived" access token (lasts 60 days) which we store in the DB and use when making requests. When that one expires, the user has to go and get a new access token again.

At this point I'm considering scrapping the Facebook API altogether and [doing what we did for Google+](https://github.com/jaredatch/EA-Share-Count/blob/issue/57/includes/class-core.php#L408-L421) and simply scrape the count from the button.

**Comment by billerickson** [comment]
I created a Facebook App called "EA Share Count", then used its app id and secret key to try and generate a long-lived user token from my user token.

```php
$user_token = ea_share()->admin->settings_value( 'fb_access_token' );
$app_id = 'xxx';
$app_secret = 'xxx';
	
$url = 'https://graph.facebook.com/oauth/access_token?grant_type=fb_exchange_token&amp;client_id=' . $app_id . '&amp;client_secret=' . $app_secret . '&amp;fb_exchange_token=' . $user_token;
$response = wp_remote_get( $url );
ea_pp( $response );
```

It didn't work. I got the following error: 

```
stdClass Object
(
    [error] => stdClass Object
        (
            [message] => Missing client_id parameter.
            [type] => OAuthException
            [code] => 101
            [fbtrace_id] => EI/mt+EfkDn
        )

)
```

I tried swapping out the app id and secret with those of another app I have (a client's that uses it for facebook comments), and that didn't work either.

**Comment by billerickson** [comment]
It appears people will need to create a Facebook App and get an App Token rather than a User Token.

I've updated the settings page to include [this link](https://smashballoon.com/custom-facebook-feed/access-token/) that walks through setting it up. Basic steps:
1. Log into developers.facebook.com
2. Click "Add a New App"
3. Give it a name, category, and prove you're human on the security check.
4. Copy the App ID and App Secret
5. Paste in a form on the that page, and it will give you an access token.

The only thing that worries me is the access token doesn't have the same info as any other access token I've seen. Here's the one I created for my website, billerickson.net:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1X180n3l2i2S0E2L430H/Screen%20Shot%202016-08-15%20at%2011.15.10%20AM.png?v=c01df17f)

Here's a standard user token (expires in an hour)
![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/4214071b2j0n3u300o3T/Screen%20Shot%202016-08-15%20at%2011.16.09%20AM.png?v=54b430f1)

And here's a permanent token a client of mine is using (waiting to hear back how they created it):
![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2E3y1E3n2f2Y28351A1n/Screen%20Shot%202016-08-15%20at%2011.17.36%20AM.png?v=0eb4e170)

I think the difference is that the first screenshot is an App Access Token, while the second two are User Access Tokens.


Regarding the code in [this comment](https://github.com/jaredatch/EA-Share-Count/issues/57#issuecomment-239623147) - Daniel Bachhuber pointed out I had `&amp;` instead of `&` in the URL. When I made that change I got the following error:

```
stdClass Object
(
    [error] => stdClass Object
        (
            [message] => The access token does not belong to application 1054082501314087
            [type] => OAuthException
            [code] => 1
            [fbtrace_id] => HzBanK7qJ3r
        )

)
```

**Comment by billerickson** [comment]
Here's a way to test SharedCount.com vs Facebook API results: https://gist.github.com/billerickson/e60b4d05f1da50b0e689bced628a6fc3

I placed it in my Core Functionality plugin for a local copy of my live site. It uses [ea_is_dev_site()](https://github.com/billerickson/EA-Core-Functionality/blob/master/inc/dev-tools.php#L99), [ea_production_url()](http://www.billerickson.net/code/ea-share-count-use-production-url/) and [ea_pp()](https://github.com/billerickson/EA-Core-Functionality/blob/master/inc/dev-tools.php#L11), so make sure you have those in your CF plugin.

Example Results:

```
SharedCount
stdClass Object
(
    [StumbleUpon] => 
    [Facebook] => stdClass Object
        (
            [commentsbox_count] => 0
            [click_count] => 0
            [total_count] => 105
            [comment_count] => 3
            [like_count] => 21
            [share_count] => 81
        )

    [GooglePlusOne] => 4
    [Twitter] => 
    [Pinterest] => 0
    [LinkedIn] => 1
)
Direct from Facebook
Array
(
    [Facebook] => Array
        (
            [share_count] => 105
            [like_count] => 105
            [comment_count] => 0
            [total_count] => 105
        )

    [Twitter] => 0
    [Pinterest] => 0
    [LinkedIn] => 0
    [GooglePlusOne] => 0
    [StumbleUpon] => 0
)
```


I can now check this every now and then to see if SharedCount.com still works, and if the Facebook Access Token I generated above is still valid.

**Comment by billerickson** [comment]
I've added an admin notice, and the more information links here: [No longer using SharedCount.com](https://github.com/jaredatch/EA-Share-Count/wiki/No-longer-using-SharedCount.com)

Let me know if you think any of the text should be changed.

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/0M3M2w2b220g1x232D0G/Screen%20Shot%202016-08-15%20at%202.52.18%20PM.png?v=692e1317)

**Comment by engagedcount** [comment]
@billerickson just a heads up that engagedcount.com was started to fill the void of sharedcount shutting down - it handles the auth to the various services so your users would no longer need to configure anything again.
