### ISSUE TITLE
Comment and share not working on pages

### ISSUE THREAD

**Issue by conandor** [jaredatch/EA-Share-Count#82]
By using fb debugging tools (https://developers.facebook.com/tools/debug/sharing/)

Debugging result show missing fb:app_id and different og:type and 
> Inferred Property: The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.

However on posts everything was fine.

Sample page: http://pekchekkia.com/about
Sample post: http://pekchekkia.com/2107

**Comment by billerickson** [comment]
This plugin does not add open graph tags, it simply displays the share button. You should use Yoast SEO or a similar plugin for adding and managing your open graph tags.
