### ISSUE TITLE
v2.0 features

### ISSUE THREAD

**Issue by billerickson** [jaredatch/EA-Share-Count#89]
- [x] Set minimum PHP version (5.5 or 5.6+)
- [ ] Add support for multiple URLs per post. Can be set with a site-wide filter or per-post using GUI ([screenshot](https://cl.ly/3i1G2v1u212l))
- [ ] On settings page, add checkbox "include non-SSL version of URLs" which automatically adds http version as alternative url sitewide
- [ ] Remove bubble style
- [ ] Add additional styles ( https://cl.ly/063n0R451734 https://cl.ly/3p45011e123G https://cl.ly/232b3x1J2x20 )
- [ ] Use SASS for styling, minified for production (via gulp)
- [ ] Use minified JS for production (via gulp)
- [ ] Integrate [Codeception tests](http://codeception.com/)
- [ ] Refactor as a new plugin (Share Count Plugin or something similar)

**Comment by jaredatch** [comment]
FYI added an item to the list and reorder to order in which items will most likely be completed.

**Comment by jaredatch** [comment]
Closing. Migrated these to issues in the new repo.

https://github.com/jaredatch/Shared-Counts/issues
