### ISSUE TITLE
HTTPS for all sharing links

### ISSUE THREAD

**Issue by billerickson** [jaredatch/EA-Share-Count#90]
A client noticed that some of our sharing links are http ([see here](https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-front.php#L409-L453)). Everything should be https.

Here's what I'm using in our core functionality plugin to fix this until the new version of EASC is out.

```php
/**
 * HTTPS for all sharing links
 *
 */
function ea_https_for_sharing_links( $link ) {
	$link['link'] = str_replace( 'http://', 'https://', $link['link'] );
	return $link;
}
add_filter( 'ea_share_count_link', 'ea_https_for_sharing_links' );
```

**Comment by jaredatch** [comment]
This is already fixed in the refactor, had this exact issue with the client I switched to SSL lol
