### ISSUE TITLE
Shortcode Elementor

### ISSUE THREAD

**Issue by Celestialpetals** [jaredatch/EA-Share-Count#91]
What is the shortcode for Elementor plugin?  Also what is the shortcode for any post or builder?

**Comment by billerickson** [comment]
This plugin does not use shortcodes as it's not designed to be manually inserted inside post/page content. You can use the [location filter](https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-front.php#L109) to reposition its theme location, or the [display method](https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-front.php#L253) to display it elsewhere in your theme.

But if you must have a shortcode, [add this](https://gist.github.com/billerickson/858ce03c85e317cd2b9cabbadd3991f9) to your theme's functions.php file or [Core Functionality](https://www.billerickson.net/core-functionality-plugin/) plugin. You can then display it like: `[ea_share_count location="about-page" style="slim"]` 

The shortcode is a wrapper for `ea_share()->front->display( $location, $echo = false, $style );`
