### ISSUE TITLE
Icons for Popular Mobile Apps - Whatsapp/ Telegram

### ISSUE THREAD

**Issue by IkeTen** [jaredatch/EA-Share-Count#92]
Hi and thanks for Creating EA Share Count. 
Will there be support for Whatsapp (especially) or Telegram in the future?  There apps have many users and very good platforms to share posts. I thinks that's the only missing for this awesome plugin. 
For the time being, is there a there a way to customize EA Share Count to include other social buttons like Whatsapp?

Thank you.

**Comment by billerickson** [comment]
I don't believe we will be adding new sharing buttons to the core plugin, but you can easily add your own with the built-in filters.

Here's an example of adding a Reddit share button: https://gist.github.com/billerickson/969f8ef0e980fe6e6345

The `ea_share_count_admin_services` filter lets you control what services appear in the settings page, so you can add that share button to the list.

The `ea_share_count_link` filter lets you control the frontend display of that share button.

**Comment by IkeTen** [comment]
Thanks Bill.
