### ISSUE TITLE
buttons on front page

### ISSUE THREAD

**Issue by democracychronicles** [jaredatch/EA-Share-Count#99]
You said we should 'use ea_share()->front->display() in your theme to display the buttons' but how do i put them into my sidebar. Is there a shortcode? I just want the buttons on my front page. I use Genesis News Pro theme.

https://democracychronicles.org/

**Comment by billerickson** [comment]
The EA Share Count plugin has been forked to a new plugin, [Shared Counts](https://github.com/jaredatch/Shared-Counts). That plugin does have a shortcode: `[shared_counts]`

**Comment by democracychronicles** [comment]
Thanks for all of your good work Bill! I dont know what u mean by forked.
And im having trouble downloading Shared Counts at the link you sent as
well.

**Comment by billerickson** [comment]
By "forked" I mean we've renamed the plugin "Shared Counts" and are continuing development [over there](https://github.com/jaredatch/Shared-Counts/). This plugin (EA Share Counts) is no longer being developed, so I recommend you use Shared Counts instead.

You can download the plugin here: https://github.com/jaredatch/Shared-Counts/archive/develop.zip

**Comment by jaredatch** [comment]
Also worth adding that it will be available on WP.org in the near future.

**Comment by democracychronicles** [comment]
Thanks for your responsiveness on this! I have installed "Shared Counts"
now but it is having problems appearing correctly on my website. I use the
News Pro Genesis theme. No matter what 'Share Button Style' i used, the
icons are not displayed correctly. Right now Im gonna leave your plugin
installed on my posts so you can see the problem. Here is an example of how
the problem looks on a random page:

https://democracychronicles.org/using-paper-ballots/

**Comment by democracychronicles** [comment]
thank you so much Bill. My website is based on  your advice, tutorials and
everything else. If those bugs are fixed though, should i redownload or the
fix not ready for public use?

**Comment by billerickson** [comment]
It would be great if you could redownload and test. It should be working fine now. Or you can wait for the public release, which should be in a few weeks. It's really up to you. 

If you want to keep using EA Share Count, you can add this to your theme's functions.php file to create a shortcode called `[ea_share_count]`: https://gist.github.com/billerickson/97a34da5e5f2c69b6d4b8805de05f4ed

**Comment by democracychronicles** [comment]
A million thanks! Ok i did a redownload and test. Now it looks fine but it
will save as only the 'icon' Share Button Style. If i try to save settings
as any other style is resets to icon.

**Comment by democracychronicles** [comment]
sorry. now this problem with display seems to be gone but the plugin
remains a bit delicate. I refreshed my cache in genesis and it reset and
deleted settings on your plugin. for now i reset it and its working so im
happy and will let ya know if there are problems.

**Comment by billerickson** [comment]
Since this is a new plugin, the settings from EA Share Count do not carry over to Shared Counts. You'll need to manually re-enter them.
